export const adminTypes = {
  // homepage management----------//news

  GET_DISTRICT_DATA_PENDING: "GET_DISTRICT_DATA_PENDING",
  GET_DISTRICT_DATA_SUCCESS: "GET_DISTRICT_DATA_SUCCESS",
  GET_DISTRICT_DATA_FAILED: "GET_DISTRICT_DATA_FAILED",

  GET_DISTRICT_OFFICER_PENDING: "GET_DISTRICT_OFFICER_PENDING",
  GET_DISTRICT_OFFICER_SUCCESS: "GET_DISTRICT_OFFICER_SUCCESS",
  GET_DISTRICT_OFFICER_FAILED: "GET_DISTRICT_OFFICER_FAILED",

  GET_DISTRICT_OFFICER_DETAILS_PENDING: "GET_DISTRICT_OFFICER_DETAILS_PENDING",
  GET_DISTRICT_OFFICER_DETAILS_SUCCESS: "GET_DISTRICT_OFFICER_DETAILS_SUCCESS",
  GET_DISTRICT_OFFICER_DETAILS_FAILED: "GET_DISTRICT_OFFICER_DETAILS_FAILED",

  GET_MANAGE_BDO_PENDING: "GET_MANAGE_BDO_PENDING",
  GET_MANAGE_BDO_SUCCESS: "GET_MANAGE_BDO_SUCCESS",
  GET_MANAGE_BDO_FAILED: "GET_MANAGE_BDO_FAILED",

  GET_BDO_DETAILS_PENDING: "GET_BDO_DETAILS_PENDING",
  GET_BDO_DETAILS_SUCCESS: "GET_BDO_DETAILS_SUCCESS",
  GET_BDO_DETAILS_FAILED: "GET_BDO_DETAILS_FAILED",

  GET_BLOCK_DATA_PENDING: "GET_BLOCK_DATA_PENDING",
  GET_BLOCK_DATA_SUCCESS: "GET_BLOCK_DATA_SUCCESS",
  GET_BLOCK_DATA_FAILED: "GET_BLOCK_DATA_FAILED ",

  
};


