export const adminTypes = {
  
  // homepage management----------//news


  GET_DISTRICT_DATA_PENDING: "GET_DISTRICT_DATA_PENDING",
  GET_DISTRICT_DATA_SUCCESS: "GET_DISTRICT_DATA_SUCCESS",
  GET_DISTRICT_DATA_FAILED: "GET_DISTRICT_DATA_FAILED",

  GET_DISTRICT_OFFICER_PENDING: "GET_DISTRICT_OFFICER_PENDING",
  GET_DISTRICT_OFFICER_SUCCESS: "GET_DISTRICT_OFFICER_SUCCESS",
  GET_DISTRICT_OFFICER_FAILED: "GET_DISTRICT_OFFICER_FAILED",


  GET_DISTRICT_OFFICER_DETAILS_PENDING: "GET_DISTRICT_OFFICER_DETAILS_PENDING",
  GET_DISTRICT_OFFICER_DETAILS_SUCCESS: "GET_DISTRICT_OFFICER_DETAILS_SUCCESS",
  GET_DISTRICT_OFFICER_DETAILS_FAILED: "GET_DISTRICT_OFFICER_DETAILS_FAILED",

  // SET_LOADING_PENDING: "SET_LOADING_PENDING",
  // SET_LOADING_SUCCESS: "SET_LOADING_SUCCESS",
  // SET_LOADING_FAILED: "SET_LOADING_FAILED",
};
